## Settings
title: Ahm3D's Page
owner: "Ahmed"
url: "https://xamedz.github.io"
baseurl: "/pRoJEct-NeGYa"
permalink: /:title/
description: "This"
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "ahmed@opensecurityalliance.org"
github: "github.com/xamedz"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Cracked by Ahmed"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√AHMEDOSA"